version: '3.9'

services:
  app:
    build: .
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
    restart: always
  
  db:
    image: mongo:7
    volumes:
      - db:/data/db
    ports:
      - "25550:27017"
    env_file: .env
    restart: always

volumes:
  db:

networks:
  traefik-proxy:
    external: true
